### PR TITLE
Change font and color of clock, looks dope in dark mode

### PR DESCRIPTION
**Pull request by mohammad-quanit**

### CODE REVIEW

**Review by mfaheemakhtar — COMMENTED** [review]
Hey @Mohammad-Quanit, 

Thank you so much for your contribution. Unfortunately, I can't merge the PR for the following reasons.

1. The font and font color do not align with the theme. I want to keep this very simple. 

image

2. This is a part of my Twitch stream content. I want to work on it to live. 

Again, thanks for your contribution. Really appreciate that.

**Comment by mohammad-quanit** [comment]
Is this project is for someone(client) or it's just a portfolio? @mfaheemakhtar

**Comment by mfaheemakhtar** [comment]
Portfolio + Twitch content.

**Comment by mohammad-quanit** [comment]
@mfaheemakhtar  ok, i got it

**Pull request closed without merging**
